package-lock.json
package.json
src/pages/samples/Examples/components/CustomizeStyle.tsx
src/react-multi-email/ReactMultiEmail.tsx
src/react-multi-email/isEmail.tsx
src/react-multi-email/style.css

I added autocomplete function.
when you type some email in inputbox, you can see the autocompleted email lists under the inputbox.
This can save your time to type those things.
If you want to add other domains you can fix your code.
https://github.com/JeonHyungJin/react-multi-email/blob/master/src/react-multi-email/ReactMultiEmail.tsx#L71
```
result = ['gmail.com', 'naver.com', 'daum.net'].map(domain => `${value}@${domain}`);
```
If you want to add, modify the domain list, try to modify this result list!
input부분에 email의 앞 부분을 입력시 미리 작성해 놓은 도메인을 이용해서 자동완성 기능을 구현 하였습니다.
자동완성을 위한 Domain 리스트는 
https://github.com/JeonHyungJin/react-multi-email/blob/master/src/react-multi-email/ReactMultiEmail.tsx#L71
부분에서 
```
result = ['gmail.com', 'naver.com', 'daum.net'].map(domain => `${value}@${domain}`); …
```

Autocomplete function done.

---

src/react-multi-email/ReactMultiEmail.tsx

Make react-multi-email class optional

---

.eslintrc.json
package-lock.json
package.json
src/react-multi-email/ReactMultiEmail.tsx

1. Update of the react-hot-loader to the latest version resolves the issue of invalid hook call error and state not being updated.
2. React-Multi-Email components have been refactored into functional state components using Hook.
3. Because I have used anti-patterns, it seems we need more refactoring to pull functions out to other files.

Change ReactMultiEmail.tsx to functional component

---

packages/react-multi-email/IProps.tsx
packages/react-multi-email/ReactMultiEmail.tsx

Divide Interface code to simplify ReactMultiEmail.tsx

Refactor the interface IProps of ReactMultiEmail

---

README.md
package-lock.json
package.json
packages/react-multi-email/ReactMultiEmail.tsx
packages/react-multi-email/customHooks/useEmail.tsx
pages/index.tsx

구조상 useHandler는 따로 있는게 좋을 것 같아서 빼보았습니다. 저는 hook을 통해서 각 함수가 공동 변수를 접근하도록 하는게 의도 였는데 생각대로 되지 않아서 문제였습니다. 그래서 지금 inputValue가 변경되지 않아 입력해도 보이지 않는걸로 예상됩니다. 도움 주시면 감사하겠습니다!

Change to hook

---

src/react-multi-email/ReactMultiEmail.tsx

When adding multiple emails it is way much easier to navigate when input gets auto focused

Adding auto focus to input element

---

react-multi-email/ReactMultiEmail.tsx

Patched #88 

---

react-multi-email/ReactMultiEmail.tsx

Add support for providing an initial input value

feat: add initial input value

---

react-multi-email/ReactMultiEmail.tsx

I want to pass just some classnames directly to the input, which isn't possible now.
It would be nice to have an extra prop to achieve this like I did in this PR

Pass className to input too

---

test/style.test.tsx

A test code for the style prop

test: style prop

---

test/id.test.tsx

This test code check two things
- Does an element have an `id` that you as a props
- Check element found by `querySelector` with `id `delivered through props, element tag is `input`

test: id props

---

test/onFocus.test.tsx

onFocus 함수를 테스트했습니다.
1. input 요소에 focus event를 발생시킨 후 focus 됐는지 여부 파악 
2. prop으로 전달하는 onFocus 함수가 동작하는지 여부 파악
react-testing-library에 대한 이해도가 아직 부족해서 피드백해주시면 적극 반영하겠습니다 😃

test : onFocus test

---

test/autoFocus.test.tsx

autoFocus Prop 테스트 진행했습니다.
- autoFocus 속성이 ture/false로 설정됐을 때, 입력란이 자동으로 포커스/포커스아웃 되는지 확인
제대로 test 진행되지 않거나 개선사항 있다면 피드백 부탁드립니다. 😃

test: autoFocus prop

---

test/autoFocus.test.tsx
test/noClass.test.tsx

noClass Prop 테스트 진행했습니다.
- noClass 속성이 ture/false로 설정됐을 때, 'react-multi-email' class의 유무 파악
제대로 test 진행되지 않거나 개선사항 있다면 피드백 부탁드립니다. 😃

Test: noClass prop

---

test/onChange.test.tsx

onChange prop에 대하여 테스트 코드를 작성했습니다.
"Backspace", "Enter", focus out에 의해 이메일이 추가되거나 삭제될 때를 테스트하였습니다.
감사합니다!

test: onChange prop

---

react-multi-email/ReactMultiEmail.tsx

Refactor simplify findEmailAddress logic

---

react-multi-email/ReactMultiEmail.tsx

#127 PR에 대한 부수적인 수정 진행하였습니다. 확인해주시고 필요하다면 merge 부탁드립니다. 
- React Hook React.useCallback에 'allowDisplayName' 및 'stripDisplayName' 종속성 추가
- 쌍 따옴표를 따옴표로 변경(Prettier 설정)

fix: Add dependencies to React Hook React.useCallback

---

test/onDisabled.test.tsx

- 함수 호출이 의도한 바와 다름
- keyDown 메서드는 findEmailAddress를 호출하지 않기 때문에 의도한 test가 진행되지 않음
위 사유로 기존 test code fix를 진행하였습니다. 😢

fix: replace testing code method 'keyDown' to 'keyUp'

---

test/onKeyUp.test.tsx

* Enter 키를 눌렀을 때 'onKeyUp' 호출되는지 확인 
* 'fireEvent.keyDown'을 사용하여 'Tab' 키를 누를 때 'onKeyUp' 함수가 호출되지 않는지 확인

test onKeyUp props

---

test/enable.test.tsx

enable props 테스트했습니다.
1. enable 함수가 잘 동작하는지 테스트했습니다. 
2. enable 함수의 성공 여부에 따라서 disabled 함수가 잘 동작하는지 테스트하였습니다.

test : enable props

---

examples/BasicExample.tsx
react-multi-email/ReactMultiEmail.tsx

Hotfix #153

---

test/onChangeInput.test.tsx

onChangeInput 함수를 테스트했습니다.
- input에 값을 입력하고 onChangeInput 함수가 실행하는지와 onChangeInput에 값이 잘 전달됐는지를 테스트했습니다.

onChangeInput prop test

---

test/onKeyDown.test.tsx

* input 요소에 값을 입력한 후 Enter 키를 누르면 onKeyDown 콜백이 호출되는지 확인
* input 요소에 값을 입력한 후 Backspace 키를 누르면 onKeyDown 콜백이 호출되는지 확인

Test onKeyDown Props

---

test/onBlur.test.tsx

onBlur test 진행했습니다.
1. focus된 적이 없는 경우 onBlur가 호출되지 않음 확인
2. input area가 blur된 경우 onBlur 호출 확인

onBlur prop test

---

test/getLabel.test.tsx

* test whether getLabel is called on entering new valid email
* test whether elements returned by getLabel have the right index and email
* test whether removeEmail is called on clicking element

test getLabel prop

---

test/className.test.tsx

* check whether className is correctly assgined
* (edit: 230920) check in the case className prop not provided

test className prop
