axisj/react-multi-email

- dist/index.d.ts
- dist/package.json
```
...
(16,33): Could not find a declaration file for module 'react-multi-email'. '.../node_modules/react-multi-email/commonjs/index.js' implicitly has an 'any' type.
Try `npm install @types/react-multi-email` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-multi-email';`
```
> Fix : type not declaration problem

- src/react-multi-email/isEmail.tsx
이슈 8번
https://github.com/jsdevkr/react-multi-email/issues/8
isFQDN 함수 options 순서를 바꾸면 좋겠다는 이슈를 간단하게 바꾸어서 해결했습니다!
> issue #8 order changed

- src/react-multi-email/style.css
- src/samples/Basic.tsx
- src/samples/CustomizeStyle.tsx
I suppose to add a little fix for long email addresses in the form. They overflow the form with markup breaks, if I input email addresses with more than 100 symbols (in little width form).
> Fix long email addresses overflow

- src/react-multi-email/ReactMultiEmail.tsx
If duplicate email addresses were copied from Notepad and pasted to the ReactMultiEmail tag, duplicate addresses would appear. So I fix it.
> Fix the bug of duplicated email at paste

- dist/commonjs/ReactMultiEmail.d.ts
- dist/commonjs/ReactMultiEmail.js
- package.json
- src/react-multi-email/ReactMultiEmail.tsx
**1 - Update react, react-dom, react-hot-loader**
: Hooks only work with 16.8.0 and above. Therefore, react was updated to 16.8.0. 
react-dom has been updated accordingly.
react-hot-loader caused the 'invalid  hook call' bug.
This bug is gone when I updated react-hot-loader to latest version.
**2 - Refactoring to Hook codes**
: delete useless lifecycle function, and convert methods to function variables.
replace class-based state with state of hook version.
> Refactoring Class-based codes to Hook 

- dist/style.css
- src/react-multi-email/style.css
This extends the input field to take the rest of the line space so that it won't cut off on long email
> Expend input box to take the rest line space

- src/react-multi-email/ReactMultiEmail.tsx
In current release it is not possible to navigate to next field by pressing tab key. It used to work correctly in 0.5.0 ( DEMO: https://codesandbox.io/s/react-multi-email-forked-4bzz0?file=/src/index.tsx ). This pull requests reverts invalid behaviour of preventing defaults on tab key press.
> Fixing issue of not being able to move to next field by pressing tab

- README.md
Refers to: https://github.com/axisj/react-multi-email/issues/103
The wrong reference to the styles.css in v 1.0.3 was fixed.
> upd README with styles.css import

- react-multi-email/ReactMultiEmail.tsx
Hi,
I suggest this small change which allows to avoid line break for input when not necessary.
From: 
To:
> Avoid line break when not necessary

- README.md
- react-multi-email/ReactMultiEmail.tsx
In this Pull Request, 
Problem: 
I can't manage the `input` element `autoComplete` prop.
Solution: 
Add `autoComplete` prop to `ReactMultiEmail` with type.
The Way of Development:
- I added to `autoComplete` prop to `ReactMultiEmail` to handle the `input` element `autoComplete` prop. I thought that it help us to get this point.
- Update Read.me file to keep props up to date.
- Remove unused `onChangeInput` dependency from useEffect, line: 166
Note: If you think this development is a chore and there is something that I can't be aware of or a way that I can handle my problem, please close this pull request and let me know the way. :)
> feat: add autocomplete prop

- react-multi-email/ReactMultiEmail.tsx
@thomasJang 해당 로직으로 돌려도 돌아갈 것 같은데 검증 부탁드리겠습니다.!
결국 내부 emails state에 props로 들어오는 `emails`가 세팅이 되어야해서 해당 `useEffect` 구문이 있는것 같은데
그렇다면 초기 useState값에 세팅이 되어도 기존 로직과 동일하게 동작하지 않을까 싶어서 의견 드립니다
+ 추가로 props로 들어오는 email에 대해서도 validation check가 필요할 것 같아서 initialEmailAddress를 추가했습니다.
> Fix logic about props 'emails'

- react-multi-email/ReactMultiEmail.tsx
안녕하세요. backspace keyup 이벤트에서 이메일을 입력하도록 되어있는데, 이것이 의도된 행동인지 궁금하여 PR을 생성하였습니다.
https://github.com/axisj/react-multi-email/assets/52730665/8432a917-8526-467f-a367-aa8b83b1ef9a
위 사진처럼 백스페이스를 눌렀을 때 이메일이 입력되고 있습니다.
제가 정확히 파악하지 못한 행동일수도 있을 것 같아 궁금하여 여쭤봅니다. @thomasJang 확인해주시면 감사하겠습니다! 🔥
> Fix unexpected backspace keyup event handling

- react-multi-email/ReactMultiEmail.tsx
- test/allowDuplicate.test.tsx
> Support email duplicating

- react-multi-email/ReactMultiEmail.tsx
This fixes copy and paste for multiple emails in a row. @thomasJang Looks like after a bit more extensive testing, checking `if array.length === 1` is not what we want to do. When trying to copy-paste emails copied from Google this check does not work.
Sorry for my mistake, can you review and see if I am missing anything? Thanks.
> fix(reactmultiemail): fix copy and paste of multiple emails at a time

- react-multi-email/ReactMultiEmail.tsx
trim emails with space after comma. If you copy something like: email1@domain.com, email2@domain.com, email3@domain.com the space is
> fix(reactmultiemail.tsx): trim emails with space after comma

- react-multi-email/ReactMultiEmail.tsx
**[ 관련 이슈 ]** 
#166 
**[문제사항]**
해당 부분을 살펴보고 테스트해보니까 ,(콤마) ;(세미콜론) 공백(space) 모두 에러가 발생했고 배열이 비어있을때 `arr[0].trim()`하는 과정에서 에러가 발생했던 것 같아 해당 부분을 제거하려고 했으나 다른 이슈와 연관(#165)되어 있어서 undefined일때 return하는 방식으로 해결하였습니다.
> fix : undefined trim error

- react-multi-email/ReactMultiEmail.tsx
- react-multi-email/style.css
📌 이슈 (#168)
기존에 placeholder가 foucs될때 아래와 같이 사라지는 이슈가 있었습니다. 
**수정 사항**
focus될때 display:none을 통해 placeholder를 제거해주는 부분을 제거하고 값이 있으면 지우는 로직으로 변경하였습니다!
> fix : placeholder issue

- react-multi-email/ReactMultiEmail.tsx
- test/allowDuplicate.test.tsx
Either with malicious intent or unknowingly, a user can enter same email multiple times when not checks for case sensitivity.
This PR adds `toLowerCase()` check when adding new email so duplicate checks are robust.
> Handle case insensitive duplicate emails

- components/Nav.tsx
- examples/AsyncValidateExample.tsx
- pages/asyncValidate.tsx
- react-multi-email/ReactMultiEmail.tsx
- test/emails.test.tsx
- test/utils/sleep.ts
enter키로 email을 입력할 때, validateEmail 함수가 false를 반환하거나 오류가 발생하는 경우 스피너가 멈추지 않는 문제 수정
> fix: stop spinner when email validation by Promise fails

- README.md
- examples/BasicExample.tsx
- react-multi-email/ReactMultiEmail.tsx
- test/emails.test.tsx
- test/enable.test.tsx
- test/validateEmail.test.tsx
https://github.com/axisj/react-multi-email/issues/104
> add inputValue prop #104
